# Generated by Django 6.0.3 on 2026-05-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
